apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: services-execute
spec:
  replicas: 1
  selector:
    matchLabels:
      app: execute
  template:
    metadata:
      labels:
        app: execute
    spec:
      containers:
        - name: execute
          image: {{ .Values.images.execute}}:{{ .Values.versions.execute }}
          env:
            - name: KAFKA_BROKER
              value: {{ .Values.resources.kafka.broker }}
            - name: MONGO_URL
              value: {{ .Values.resources.mongo.url }}
            - name: MONGO_DATABASE
              value: {{ .Values.resources.mongo.database }}
