apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: services-schedule
spec:
  replicas: 1
  selector:
    matchLabels:
      app: schedule
  template:
    metadata:
      labels:
        app: schedule
    spec:
      containers:
        - name: schedule
          image: {{ .Values.images.schedule}}:{{ .Values.versions.schedule }}
          env:
            - name: KAFKA_BROKER
              value: {{ .Values.resources.kafka.broker }}
            - name: MONGO_URL
              value: {{ .Values.resources.mongo.url }}
            - name: MONGO_DATABASE
              value: {{ .Values.resources.mongo.database }}
