kind: Service
apiVersion: v1
metadata:
  name: services-schedule
spec:
  type: LoadBalancer
  selector:
    app: schedule
  ports:
  - name: http
    port: 80
    targetPort: {{ .Values.ports.schedule.api }}
