version: '3'

services:
  service-revisions:
    image: xalgorithms/xadf-revisions-service:latest-development
    command: bundle exec rackup -p 5000 --host 0.0.0.0
    ports:
      - 5000:5000
    environment:
      CASSANDRA_HOSTS: "cassandra"
      MONGO_URL: "mongodb://mongo:27017/xadf"
    depends_on:
      - mongo
      - kafka
      - cassandra
  # service-schedule:
  #   image: xalgorithms/service-il-schedule:0.1.2
  #   depends_on:
  #     - mongo
  #     - cassandra
  #     - kafka
  #   environment:
  #     - APPLICATION_SECRET="${SCHEDULE_APPLICATION_SECRET}"
  #   ports:
  #     - 6000:9000
    
