kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: spark-zepplin-config
  labels:
    app: spark
    release: spark
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100M
  storageClassName: "standard"
