version: '3'

services:
  service-events:    
    image: xalgorithms/service-il-events:latest-development
    ports:
      - "4200:4200"
      - "4201:4201"
    depends_on:
      - kafka
    environment:
      KAFKA_BROKER: "kafka:9092"
      PORT_API: 4200
      PORT_EVENTS: 4201
    command: npm run start-production
    
