version: '3'

services:
  service-revisions:
    image: xalgorithms/service-il-revisions-github:latest-development
    command: bundle exec rackup -p 5000 --host 0.0.0.0
    ports:
      - 5000:5000
    environment:
      CASSANDRA_HOSTS: "cassandra"
      MONGO_URL: "mongodb://mongo:27017/interlibr"
    depends_on:
      - mongo
      - cassandra
